---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Its elastic but we have to provide for specification sake